### ISSUE TITLE
can some one walk me through the deploymen

### ISSUE THREAD

**Issue by 1coolmatt8083** [titaniumnetwork-dev/Alu#12]
can someone help me through the deployment of this cause I want to deploy through vercel

**Comment by wearrrrr** [comment]
It's just the same process as deploying almost anything else that uses pnpm.
`npm i -g pnpm`
`pnpm i`
`pnpm build`
`pnpm start`
tada

**Comment by AccidentlyOP** [comment]
you cannot deploy this using vercel as alu does not support static hosts.

**Comment by solaritygh** [comment]
> you cannot deploy this using vercel as alu does not support static hosts.

vercel isn't static if i remember correctly
