### ISSUE TITLE
"Syntax Error: Cannot use import statement outside a module" on Docker

### ISSUE THREAD

**Issue by NotLawson** [titaniumnetwork-dev/Alu#14]
I am trying to run Alu in a Docker container.
It does the same thing it would usually do on a normal runtime, but just containerized.

Dockerfile:
```
FROM node:latest

COPY Alu .

RUN npm i -g pnpm
RUN pnpm i
RUN pnpm run build

CMD [ "pnpm", "start" ]
```

After running `git clone https://github.com/titaniumnetwork-dev/Alu --recurse-submodules`.
When I try to run the container however, I get the error "Syntax Error: Cannot use import statement outside a module"

I'm quite new to JS, so this probably is a simple problem to fix.

Thanks in advance,
Lawson

**Comment by NotLawson** [comment]
That's funny, I think the problem is that package.json is missing the line `"type":"module"`, but when I looked, it does have it (line 3). This is probably an issue on my end.
Thanks, 
Lawson

**Comment by wearrrrr** [comment]
Hello! Can you try pulling from node:lts instead of node:latest? Sometimes the newest version of node is a bit weird, so it's recommended to use the LTS version.

**Comment by NotLawson** [comment]
Thanks, all works now!

**Comment by NotLawson** [comment]
One more suggestion: Can you set up an automatic docker image build every update so I don't have to keep building the image?
Cheers, Lawson
