### ISSUE TITLE
Firefox becomes unresponsive

### ISSUE THREAD

**Issue by FoxMoss** [titaniumnetwork-dev/Alu#4]
The page eventually becomes unresponsive crashes on firefox. r58 says its an epoxy memory leak that is ffs fault, average rust.

**Comment by wearrrrr** [comment]
@FoxMoss Can you test if this commit fixes it? It will be deployed to the main site shortly.
Commit: https://github.com/wearrrrr/Alu/commit/774f26066b8ae7fe5b53d0bd1203fe69a9d4b3e6

**Comment by FoxMoss** [comment]
im unable to test, epoxy and libcurl wont work with a local or external wisp server on both ff and chrome. eventually both platforms become unresponsive. the wisp servers are being connected to but no connection packets are being sent. youll have to do independent testing.

**Comment by Playboyjusthegreat27** [comment]
Rammerhead keeps taking me to Google when I enter something

**Comment by myschoolisass** [comment]
> Rammerhead keeps taking me to Google when I enter something

what does this have to do with the above issue? if you have an issue with rammerhead, talk about it on _that_ proxy's issue page, not on this issue

**Comment by wearrrrr** [comment]
I just tested this again and I can't recreate anymore, closing!
