### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by Playboyjusthegreat27** [titaniumnetwork-dev/Alu#9]
I have an issue where the screen goes blue and stops responding. I tried switching proxies and the issue still persists.

**Comment by Notplayingallday383** [comment]
Could you prehaps provide more info

**Comment by Playboyjusthegreat27** [comment]
It will let me search something on Google then it'll freeze and the screen will turn blue

**Comment by Playboyjusthegreat27** [comment]
Then it'll prompt me to close the page

**Comment by solaritygh** [comment]
> Then it'll prompt me to close the page

It seems like your teachers might be closing the tab through GoGuardian. Try testing it at home.

**Comment by Playboyjusthegreat27** [comment]
Yeah they just blocked it entirely :(

**Comment by solaritygh** [comment]
> Yeah they just blocked it entirely :(

I'd recommend hosting it yourself on vercel

**Comment by Playboyjusthegreat27** [comment]
How do I do that

**Comment by solaritygh** [comment]
> How do I do that

Clone the repository, and deploy it with vercel. You can find a lot of online guides on that
